const Router = require('express')
const router = new Router()
const userRouter = require('./userRouter')
const deviceRouter = require('./deviceRouter')
const brandRouter = require('./brandRouter')
const typeRouter = require('./typeRouter')
const basketRouter = require('./basketRouter')
const favouritesRouter = require('./favouritesRouter')
const PromoRouter = require('./PromoCodeRouter')
const OrderRouter = require('./OrderRouter')
const NewsRouter = require('./NewsRouter')
const SalesRouter = require('./SalesRouter')

router.use('/user', userRouter)
router.use('/type', typeRouter)
router.use('/brand', brandRouter)
router.use('/device', deviceRouter)
router.use('/basket', basketRouter)
router.use('/favourites', favouritesRouter)
router.use('/promo', PromoRouter)
router.use('/order', OrderRouter)
router.use('/news', NewsRouter)
router.use('/sales', SalesRouter)

module.exports = router